from selenium.webdriver.common.by import By

class Locators:
    LOGIN_H2 = (By.XPATH, ".//h2[text()='Вход']")
    LOGIN_BUTTON = (By.XPATH, ".//button[text()='Войти']")
    LOGIN_IN_ACCOUNT_BUTTON = (By.XPATH, ".//button[text()='Войти в аккаунт']")
    EMAIL_INPUT = (By.XPATH, ".//input[@name='name']")
    PASSWORD_INPUT = (By.XPATH, ".//input[@type='password']")
    PROFILE_TITLE = (By.XPATH, ".//a[text()='Профиль']")
    CONSTRUCTOR_BUTTON = (By.XPATH, ".//p[text()='Конструктор']")
    CONSTRUCTOR_TITLE = (By.XPATH, ".//h1[text()='Соберите бургер']")
    INGREDIENT_1 = (By.XPATH, ".//a[contains(@class,'BurgerIngredient_ingredient')]")
    CONSTRUCTOR_BASKET = (By.XPATH, ".//ul[contains(@class,'BurgerConstructor')]")
    MODAL_WINDOW = (By.XPATH, ".//div[contains(@class,'Modal_modal')]")
    INGREDIENT_DETAIL = (By.XPATH, ".//h2[contains(@class,'Modal_modal__title')]")
    CLOSE_BUTTON = (By.XPATH, ".//button[contains(@class,'Modal_modal__close')]")
    COUNTER = (By.XPATH, ".//div[contains(@class,'counter_counter')]")
    CREATE_ORDER_BUTTON = (By.XPATH, ".//button[text()='Оформить заказ']")
    PROFILE_BUTTON = (By.XPATH, ".//p[text()='Личный Кабинет']")
    ORDER_HISTORY_BUTTON = (By.XPATH, ".//a[text()='История заказов']")
    ORDER_STATUS = (By.XPATH, "(.//div[contains(@class,'Modal_modal__textContainer')]/p)[1]")
    MODAL_TITLE = (By.XPATH, ".//h2[contains(@class,'Modal_modal__title')]")
    FEED_BUTTON = (By.XPATH, ".//p[text()='Лента Заказов']")
    ORDER_ITEM = (By.XPATH, "(.//li[contains(@class,'OrderHistory_listItem')])[1]")
    ORDER_FEED_TITLE = (By.XPATH, ".//h1[text()='Лента заказов']")
    ORDER_MODAL_WINDOW = (By.XPATH, ".//div[contains(@class,'Modal_orderBox')]")
    DETAILS = (By.XPATH, ".//p[text()='Cостав']")
    MODAL_OPENED = (By.XPATH, ".//div[contains(@class,'Modal_modal_opened')]")
    ORDERS_P = (By.XPATH, ".//div[contains(@class,'OrderHistory_textBox')]/p[contains(@class,'text_type_digits-default')]")
    ORDERS_HISTORY = (By.XPATH, ".//div[contains(@class,'OrderHistory_orderHistory')]")
    ORDER_HISTORY_LIST = (By.XPATH, f".//div[contains(@class,'OrderHistory_orderHistory')]")
    ORDER_HISTORY_LIST_ITEM = (By.XPATH, f".//ul[contains(@class,'OrderHistory_profileList')]/li/a/div/p[contains(@class,'text_type_digits')]")
    ORDER_FEED_LIST = (By.XPATH, f".//ul[contains(@class,'OrderFeed_list')]")
    ORDER_FEED_LIST_ITEM = (By.XPATH, f".//li[contains(@class,'OrderHistory_listItem')]/a/div/p[contains(@class,'text_type_digits')]")
    COMPLETED_ALL_TIME = (By.XPATH, "(.//p[contains(@class,'OrderFeed_number')])[1]")
    COMPLETED_TODAY = (By.XPATH, "(.//p[contains(@class,'OrderFeed_number')])[2]")
    ORDER_NUMBER = (By.XPATH, ".//h2[contains(@class,'Modal_modal__title')]")
    ORDERS_IN_PROGRESS = (By.XPATH, ".//ul[contains(@class,'OrderFeed_orderListReady')]/li[contains(@class,'text_type_digits')]")
    PROFILE_LINK = (By.XPATH, ".//a[text()='Профиль']")
    FORGOT_PASSWORD_BUTTON = (By.XPATH, ".//a[text()='Восстановить пароль']")
    PASSWORD_RECOVERY_H2 = (By.XPATH, ".//h2[text()='Восстановление пароля']")
    HIDE_PASSWORD_BUTTON = (By.XPATH, ".//div[contains(@class ,'input__icon')]")
    INPUT_STATUS_ACTIVE = (By.XPATH, ".//div[contains(@class ,'input_status_active')]")
    RECOVERY_BUTTON = (By.XPATH, ".//button[text()='Восстановить']")
    SAVE_BUTTON = (By.XPATH, ".//button[text()='Сохранить']")
    PERSONAL_ACCOUNT_BUTTON = (By.XPATH, ".//p[text()='Личный Кабинет']")
